version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "13000:13000"
    environment:
      - NODE_ENV=production
      - PORT=13000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data: