version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "65000:65000"
    environment:
      - NODE_ENV=production
      - PORT=65000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - my-ai-chat-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "65434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - my-ai-chat-network
    # GPU サポート (NVIDIA GPU がある場合)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:

networks:
  my-ai-chat-network:
    driver: bridge