version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - PORT=8888
      - OLLAMA_URL=http://host.docker.internal:11434
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1,::1,host.docker.internal}
    restart: unless-stopped